"use client";
import { useState, useEffect } from "react";
import AppLayout from "@/components/AppLayout";

export default function ReportsPage() {
  const [chats, setChats] = useState([]);
  const [selected, setSelected] = useState(null);

  useEffect(() => {
    const saved = JSON.parse(localStorage.getItem("medibot_chats") || "[]");
    setChats(saved.reverse());
  }, []);

  const downloadPDF = (chat) => {
    const content = `
MEDIBOT HEALTH REPORT
=====================
Date: ${new Date(chat.date).toLocaleString()}
Generated by: MediBot AI Healthcare Assistant

REPORTED SYMPTOMS
-----------------
${chat.symptoms}

AI HEALTH ANALYSIS
------------------
${chat.response}

DISCLAIMER
----------
This report is generated by an AI system and provides preliminary health guidance only.
It is NOT a substitute for professional medical diagnosis or treatment.
Please consult a qualified healthcare professional for proper medical advice.

© MediBot AI Healthcare Assistant
    `.trim();

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `medibot-report-${new Date(chat.date).toISOString().split("T")[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const getSeverityBadge = (response = "") => {
    const lower = response.toLowerCase();
    if (lower.includes("high") || lower.includes("severe") || lower.includes("emergency")) return "badge-red";
    if (lower.includes("moderate") || lower.includes("consult")) return "badge-yellow";
    return "badge-green";
  };

  const getSeverityLabel = (response = "") => {
    const lower = response.toLowerCase();
    if (lower.includes("high") || lower.includes("severe") || lower.includes("emergency")) return "High Risk";
    if (lower.includes("moderate") || lower.includes("consult")) return "Moderate";
    return "Low Risk";
  };

  return (
    <AppLayout>
      <div className="space-y-6">
        <div>
          <h1 className="text-2xl font-black">📋 Health Reports</h1>
          <p className="text-slate-400 text-sm">{chats.length} AI consultation records</p>
        </div>

        {chats.length === 0 ? (
          <div className="glass-dark rounded-2xl p-16 text-center">
            <div className="text-5xl mb-4">📋</div>
            <h3 className="text-lg font-bold mb-2">No reports yet</h3>
            <p className="text-slate-400 text-sm mb-4">Complete an AI symptom consultation to generate your first report</p>
            <a href="/chat" className="btn-primary inline-block">Start AI Consultation</a>
          </div>
        ) : (
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            {/* Reports list */}
            <div className="lg:col-span-1 space-y-3">
              {chats.map((c, i) => (
                <button key={i} onClick={() => setSelected(c)}
                  className={`w-full text-left glass-dark rounded-xl p-4 transition-all border ${selected === c ? "border-sky-500/50 bg-sky-500/10" : "border-white/5 hover:border-white/20"}`}>
                  <div className="flex items-start justify-between gap-2">
                    <p className="text-sm font-medium truncate flex-1">{c.symptoms}</p>
                    <span className={getSeverityBadge(c.response)}>{getSeverityLabel(c.response)}</span>
                  </div>
                  <p className="text-xs text-slate-500 mt-2">{new Date(c.date).toLocaleDateString()} · {new Date(c.date).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</p>
                </button>
              ))}
            </div>

            {/* Report detail */}
            <div className="lg:col-span-2">
              {selected ? (
                <div className="glass-dark rounded-2xl p-6">
                  <div className="flex items-start justify-between mb-4">
                    <div>
                      <h2 className="font-bold text-lg">Consultation Report</h2>
                      <p className="text-xs text-slate-400">{new Date(selected.date).toLocaleString()}</p>
                    </div>
                    <button onClick={() => downloadPDF(selected)} className="btn-primary text-sm px-4 py-2">
                      ⬇️ Download
                    </button>
                  </div>
                  <div className="glass rounded-xl p-4 mb-4">
                    <p className="text-xs text-slate-400 mb-1 font-semibold uppercase tracking-wider">Symptoms Reported</p>
                    <p className="text-white">{selected.symptoms}</p>
                  </div>
                  <div>
                    <p className="text-xs text-slate-400 mb-2 font-semibold uppercase tracking-wider">AI Health Analysis</p>
                    <div className="prose prose-invert max-w-none text-sm text-slate-200 leading-relaxed whitespace-pre-wrap">
                      {selected.response}
                    </div>
                  </div>
                  <div className="mt-4 p-3 bg-red-950/30 border border-red-900/30 rounded-xl">
                    <p className="text-red-400 text-xs">⚠️ This AI report is for informational purposes only and does not constitute a medical diagnosis.</p>
                  </div>
                </div>
              ) : (
                <div className="glass-dark rounded-2xl p-12 text-center h-full flex flex-col items-center justify-center">
                  <div className="text-5xl mb-4">👆</div>
                  <p className="text-slate-400">Select a report to view details</p>
                </div>
              )}
            </div>
          </div>
        )}
      </div>
    </AppLayout>
  );
}
